//! Autogenerated weights for pallet_qrasl_token
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-01-01 (placeholder), STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/node-template benchmark pallet
// --chain dev
// --execution wasm
// --wasm-execution compiled
// --pallet pallet_qrasl_token
// --extrinsic "*"
// --steps 50
// --repeat 20
// --output pallets/qrasl-token/src/weights.rs
// --template ./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_qrasl_token.
pub trait WeightInfo {
    fn mint() -> Weight;
    fn transfer() -> Weight;
    fn burn() -> Weight;
}

/// Weights for pallet_qrasl_token using the Substrate node and recommended hardware.
/// Placeholder values - these should be generated by benchmarking.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    // Storage: QraslToken TotalSupply (r:1 w:1)
    // Storage: QraslToken Balances (r:1 w:1)
    fn mint() -> Weight {
        (20_000_000 as Weight) // Placeholder
            .saturating_add(T::DbWeight::get().reads(2 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
    }
    // Storage: QraslToken Balances (r:2 w:2)
    fn transfer() -> Weight {
        (25_000_000 as Weight) // Placeholder
            .saturating_add(T::DbWeight::get().reads(2 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
    }
    // Storage: QraslToken Balances (r:1 w:1)
    // Storage: QraslToken TotalSupply (r:1 w:1)
    fn burn() -> Weight {
        (22_000_000 as Weight) // Placeholder
            .saturating_add(T::DbWeight::get().reads(2 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    fn mint() -> Weight {
        RocksDbWeight::get()
            .reads(2)
            .writes(2)
            .saturating_add(20_000_000)
    }
    fn transfer() -> Weight {
        RocksDbWeight::get()
            .reads(2)
            .writes(2)
            .saturating_add(25_000_000)
    }
    fn burn() -> Weight {
        RocksDbWeight::get()
            .reads(2)
            .writes(2)
            .saturating_add(22_000_000)
    }
}
