// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: dds_manifest.proto

package manifestv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ContentManifestV1 defines the structure for a manifest that describes
// a piece of content composed of one or more data chunks.
type ContentManifestV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of CIDs for the data chunks, in order.
	// Each CID is a Base58BTC encoded SHA-256 hash of an individual data chunk.
	ChunkCids []string `protobuf:"bytes,1,rep,name=chunk_cids,json=chunkCids,proto3" json:"chunk_cids,omitempty"`
	// SHA-256 hash of the original, complete content before it was chunked.
	// This is raw 32 bytes.
	OriginalContentSha256 []byte `protobuf:"bytes,2,opt,name=original_content_sha256,json=originalContentSha256,proto3" json:"original_content_sha256,omitempty"`
	// Total size of the original, complete content in bytes.
	OriginalContentSizeBytes uint64 `protobuf:"varint,3,opt,name=original_content_size_bytes,json=originalContentSizeBytes,proto3" json:"original_content_size_bytes,omitempty"`
	// Optional: Unix timestamp (in seconds) of when the manifest was created.
	CreationTimestamp int64 `protobuf:"varint,4,opt,name=creation_timestamp,json=creationTimestamp,proto3" json:"creation_timestamp,omitempty"`
	// Optional: MIME type of the original content, if known (e.g., "image/jpeg", "text/plain").
	MimeType string `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// Optional: Filename of the original content, if applicable.
	Filename string `protobuf:"bytes,6,opt,name=filename,proto3" json:"filename,omitempty"`
	// Future-proofing: Placeholder for additional metadata key-value pairs.
	CustomMetadata map[string]string `protobuf:"bytes,7,rep,name=custom_metadata,json=customMetadata,proto3" json:"custom_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContentManifestV1) Reset() {
	*x = ContentManifestV1{}
	mi := &file_dds_manifest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentManifestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentManifestV1) ProtoMessage() {}

func (x *ContentManifestV1) ProtoReflect() protoreflect.Message {
	mi := &file_dds_manifest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentManifestV1.ProtoReflect.Descriptor instead.
func (*ContentManifestV1) Descriptor() ([]byte, []int) {
	return file_dds_manifest_proto_rawDescGZIP(), []int{0}
}

func (x *ContentManifestV1) GetChunkCids() []string {
	if x != nil {
		return x.ChunkCids
	}
	return nil
}

func (x *ContentManifestV1) GetOriginalContentSha256() []byte {
	if x != nil {
		return x.OriginalContentSha256
	}
	return nil
}

func (x *ContentManifestV1) GetOriginalContentSizeBytes() uint64 {
	if x != nil {
		return x.OriginalContentSizeBytes
	}
	return 0
}

func (x *ContentManifestV1) GetCreationTimestamp() int64 {
	if x != nil {
		return x.CreationTimestamp
	}
	return 0
}

func (x *ContentManifestV1) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ContentManifestV1) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ContentManifestV1) GetCustomMetadata() map[string]string {
	if x != nil {
		return x.CustomMetadata
	}
	return nil
}

var File_dds_manifest_proto protoreflect.FileDescriptor

const file_dds_manifest_proto_rawDesc = "" +
	"\n" +
	"\x12dds_manifest.proto\x12\x1fdigisocialblock.dds.manifest.v1\"\xc5\x03\n" +
	"\x11ContentManifestV1\x12\x1d\n" +
	"\n" +
	"chunk_cids\x18\x01 \x03(\tR\tchunkCids\x126\n" +
	"\x17original_content_sha256\x18\x02 \x01(\fR\x15originalContentSha256\x12=\n" +
	"\x1boriginal_content_size_bytes\x18\x03 \x01(\x04R\x18originalContentSizeBytes\x12-\n" +
	"\x12creation_timestamp\x18\x04 \x01(\x03R\x11creationTimestamp\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\x12\x1a\n" +
	"\bfilename\x18\x06 \x01(\tR\bfilename\x12o\n" +
	"\x0fcustom_metadata\x18\a \x03(\v2F.digisocialblock.dds.manifest.v1.ContentManifestV1.CustomMetadataEntryR\x0ecustomMetadata\x1aA\n" +
	"\x13CustomMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01BOZMgithub.com/DigiSocialBlock/EchoNet/internal/protos/dds/manifest/v1;manifestv1b\x06proto3"

var (
	file_dds_manifest_proto_rawDescOnce sync.Once
	file_dds_manifest_proto_rawDescData []byte
)

func file_dds_manifest_proto_rawDescGZIP() []byte {
	file_dds_manifest_proto_rawDescOnce.Do(func() {
		file_dds_manifest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dds_manifest_proto_rawDesc), len(file_dds_manifest_proto_rawDesc)))
	})
	return file_dds_manifest_proto_rawDescData
}

var file_dds_manifest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dds_manifest_proto_goTypes = []any{
	(*ContentManifestV1)(nil), // 0: digisocialblock.dds.manifest.v1.ContentManifestV1
	nil,                       // 1: digisocialblock.dds.manifest.v1.ContentManifestV1.CustomMetadataEntry
}
var file_dds_manifest_proto_depIdxs = []int32{
	1, // 0: digisocialblock.dds.manifest.v1.ContentManifestV1.custom_metadata:type_name -> digisocialblock.dds.manifest.v1.ContentManifestV1.CustomMetadataEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dds_manifest_proto_init() }
func file_dds_manifest_proto_init() {
	if File_dds_manifest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dds_manifest_proto_rawDesc), len(file_dds_manifest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dds_manifest_proto_goTypes,
		DependencyIndexes: file_dds_manifest_proto_depIdxs,
		MessageInfos:      file_dds_manifest_proto_msgTypes,
	}.Build()
	File_dds_manifest_proto = out.File
	file_dds_manifest_proto_goTypes = nil
	file_dds_manifest_proto_depIdxs = nil
}
